quarkus.application.name=podflow
quarkus.http.port=8080

# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/podflow
quarkus.datasource.username=podflow
quarkus.datasource.password=podflow
quarkus.hibernate-orm.database.generation=drop-and-create

# gRPC
quarkus.grpc.server.port=9000
