quarkus.application.name=podflow
quarkus.http.port=8080

# gRPC
quarkus.grpc.server.port=9000

# Database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/podflow
quarkus.datasource.username=podflow
quarkus.datasource.password=podflow

# Hibernate
quarkus.hibernate-orm.database.generation=validate

# Flyway
quarkus.flyway.migrate-at-start=true
