import type { Episode } from "../types/episode";

/** Seed data for development and testing. */
export const MOCK_EPISODES: Episode[] = [
	{
		id: "ep-001",
		title: "The Future of AI in Podcasting",
		description: "Exploring how AI tools are transforming podcast production workflows.",
		status: "PLANNING",
		guestId: "g-001",
		guestName: "Alice Chen",
		audioUrl: "",
		showNotes: "",
		publishedAt: null,
		createdAt: "2026-03-20T10:00:00Z",
		updatedAt: "2026-03-25T14:30:00Z",
	},
	{
		id: "ep-002",
		title: "Remote Recording Best Practices",
		description: "Tips and tools for high-quality remote podcast recording.",
		status: "GUEST_COORDINATION",
		guestId: "g-002",
		guestName: "Bob Williams",
		audioUrl: "",
		showNotes: "",
		publishedAt: null,
		createdAt: "2026-03-18T09:00:00Z",
		updatedAt: "2026-03-24T11:00:00Z",
	},
	{
		id: "ep-003",
		title: "Monetizing Your Podcast",
		description: "Strategies for generating revenue from your podcast.",
		status: "RECORDING",
		guestId: "g-003",
		guestName: "Carol Davis",
		audioUrl: "",
		showNotes: "",
		publishedAt: null,
		createdAt: "2026-03-15T08:00:00Z",
		updatedAt: "2026-03-23T16:00:00Z",
	},
	{
		id: "ep-004",
		title: "Sound Design for Podcasts",
		description: "Creating immersive audio experiences with music and effects.",
		status: "EDITING",
		guestId: "",
		guestName: "",
		audioUrl: "https://storage.example.com/ep-004.wav",
		showNotes: "# Sound Design\n\n- Intro music\n- Transitions\n- Ambient backgrounds",
		publishedAt: null,
		createdAt: "2026-03-10T07:00:00Z",
		updatedAt: "2026-03-22T13:00:00Z",
	},
	{
		id: "ep-005",
		title: "Building a Podcast Community",
		description: "How to grow and engage your listener community.",
		status: "REVIEW",
		guestId: "g-005",
		guestName: "Eve Johnson",
		audioUrl: "https://storage.example.com/ep-005.wav",
		showNotes: "# Community Building\n\n- Discord servers\n- Social media\n- Live events",
		publishedAt: null,
		createdAt: "2026-03-05T06:00:00Z",
		updatedAt: "2026-03-21T10:00:00Z",
	},
	{
		id: "ep-006",
		title: "Podcast SEO and Discoverability",
		description: "Optimizing your podcast for search engines and directories.",
		status: "PUBLISHED",
		guestId: "g-006",
		guestName: "Frank Lee",
		audioUrl: "https://storage.example.com/ep-006.wav",
		showNotes: "# SEO Tips\n\n- Keywords in titles\n- Show note optimization\n- Transcripts",
		publishedAt: "2026-03-20T09:00:00Z",
		createdAt: "2026-03-01T05:00:00Z",
		updatedAt: "2026-03-20T09:00:00Z",
	},
	{
		id: "ep-007",
		title: "Interview Techniques for Hosts",
		description: "Master the art of conducting engaging podcast interviews.",
		status: "PLANNING",
		guestId: "",
		guestName: "",
		audioUrl: "",
		showNotes: "",
		publishedAt: null,
		createdAt: "2026-03-22T11:00:00Z",
		updatedAt: "2026-03-26T08:00:00Z",
	},
];
